# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatetimeMcp < Formula
  desc "Self-contained date/time provider for Claude Desktop, Claude Code, and Codex"
  homepage "https://github.com/tmsdnl/datetime-mcp"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmsdnl/datetime-mcp/releases/download/v1.3.6/datetime-mcp_1.3.6_darwin_amd64.tar.gz"
      sha256 "315f936d2eb464e3c35093e796287564e213d53d41d2698c3d72bc3415c1f623"

      define_method(:install) do
        bin.install "datetime-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmsdnl/datetime-mcp/releases/download/v1.3.6/datetime-mcp_1.3.6_darwin_arm64.tar.gz"
      sha256 "47b5d1918767e481767ceabbd70b169a0664375310e04e78d05e09ed01fb195a"

      define_method(:install) do
        bin.install "datetime-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmsdnl/datetime-mcp/releases/download/v1.3.6/datetime-mcp_1.3.6_linux_amd64.tar.gz"
      sha256 "930833aa91128704af62b7407a062add1f57700f4e3c63db06db10a0bbe16c38"
      define_method(:install) do
        bin.install "datetime-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmsdnl/datetime-mcp/releases/download/v1.3.6/datetime-mcp_1.3.6_linux_arm64.tar.gz"
      sha256 "5863b686fa3a3da81c711d45ef0b26d16327281f706287697ccdc1b8e29d23ca"
      define_method(:install) do
        bin.install "datetime-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Install built-in format files by running:
        datetime-mcp format install

      Custom format files can be placed in:
        ~/.config/datetime-mcp/formats/

      To fully remove datetime-mcp, also delete that directory.
    EOS
  end

  test do
    system "#{bin}/datetime-mcp", "--version"
  end
end
